### ISSUE TITLE
sm3_hash测试类报错

### ISSUE THREAD

**Issue by Fury-Fox** [duanhongyi/gmssl#19]
>>> print(sm3.sm3_hash(b"abc"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\ProgramData\Anaconda3\lib\site-packages\gmssl\sm3.py", line 95, in sm3_hash
    msg.append(0x80)
AttributeError: 'bytes' object has no attribute 'append'

**Comment by JagnDC** [comment]
同样的错误，请问怎么解决？

**Comment by Fury-Fox** [comment]
入参类型不正确。
` n = []
  for i in hash_data[:]:
       n.append(i)
  ret = sm3.sm3_hash(n)`
