### ISSUE TITLE
sm3_hash demo cant run

### ISSUE THREAD

**Issue by miuchen** [duanhongyi/gmssl#27]
>>> from gmssl import sm3, func
>>> 
>>> if __name__ == '__main__':
...     y = sm3.sm3_hash(func.bytes_to_list(b"abc"))
...     print(y)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python2.7/site-packages/gmssl/sm3.py", line 116, in sm3_hash
    for i in range(0, group_count):
TypeError: range() integer end argument expected, got float

**Comment by miuchen** [comment]
it seams only work with python3
